
server:
  port: 8585


spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          defaultBrokerPort: 9092
          transaction:
            transactionIdPrefix: my-tr-id
            producer:
              configuration:
                retries: 1
                acks: all

      bindings:
        # binding name should match with topic name in the code, not in the destination
        my-topic:
          # destination is optional, binding name used as a destination by default
          destination: my-topic
          content-type: application/json
          consumer:
            max-attempts: 1
        my-topic-user:
          destination: my-topic-user
          content-type: application/xml
          consumer:
            max-attempts: 1
        my-topic-group:
          destination: my-topic-group
          content-type: application/xml
          consumer:
            max-attempts: 1

        my-topic-user-out:
          content-type: application/xml

        my-topic-user-out-tr:
          destination: my-topic-user-out
          content-type: application/xml
          consumer:
            max-attempts: 1
#            configuration:
#              isolation.level: read_committed
